### ISSUE TITLE
要不就放全一点，要不就不要放了，放一个残缺没法运行的工程来收费咨询，这样有意思吗

### ISSUE THREAD

**Issue by bolinli** [YuJian95/hospital-wxapp#1]

**Comment by xdmdcp** [comment]
首先这个项目绝对是可以运行起来的，有些人不会，不知道怎么运行起来，找我远程帮他运行起来，收费有什么问题？

开源难道等于可以白嫖我时间，大家都是成年人，请不要以总以为别有义务帮你解决问题。
